spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/employeemanagerdb
    username: biboran
    password: biboran
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format-sql: true

flyway:
  url: jdbc:postgresql://localhost:5432
  user: biboran
  password: biboran

page:
  size: 5
